Mappings:
  AmiRegionMap: 
    us-east-1:
      MyAMI1: "ami-0427090fd1714168b"
    us-east-2:
      MyAMI1: "ami-00db8dadb36c9815e"
    us-west-1:
      MyAMI1: "ami-03ed1381c73a5660e"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - MyAMI1
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, CF]]
      SecurityGroups:
        - !Ref VprofileSG

  VprofileSG: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and http to client host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  