Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0427090fd1714168b
      Tags:
        - Key: "Name"
          Value: "CF-instance"